#!/usr/bin/env bash

set -euo pipefail

# ============================================================
# PocketBoard dictionary generator
#
# Design goals:
#   - Hunspell dictionaries are vocabulary sources only.
#   - NEVER validate candidates word-by-word with hunspell -a.
#   - Unicode/NFC-safe vocabulary.
#   - Preserve Spanish accents and Argentine voseo.
#   - Frequency-first vocabulary selection.
#   - Curated mandatory vocabulary is always preserved.
#   - Accent-aware filtering for noisy unaccented FrequencyWords
#     variants in Spanish.
#   - "manana" is explicitly excluded from es-AR.
#   - Final .dict files are the sole source for .deletes.
#   - Maximum delete distance is 2.
#   - Deterministic output.
#   - No shell pipelines that can fail because of SIGPIPE.
#   - All generated output is written to the Android assets directory.
# ============================================================

export LANG="C.UTF-8"
export LC_ALL="C.UTF-8"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"

OUTPUT_DIR="${PROJECT_ROOT}/app/src/main/assets/dictionaries"
WORK_DIR="${PROJECT_ROOT}/build/pocketboard-dictionaries"

# ------------------------------------------------------------
# Configuration
# ------------------------------------------------------------

SOURCE_MAX_ENTRIES=500000

TOP_DISTANCE2_WORDS=15000

MAX_DELETE_WORD_LENGTH=24
MAX_DELETES_PER_WORD=3

MAX_DISTANCE=2

ES_AR_DELETE_BUDGET=2500000
EN_EN_DELETE_BUDGET=2500000
DE_DE_DELETE_BUDGET=2500000
GLOBAL_DELETE_BUDGET=7500000

# ------------------------------------------------------------
# Source URLs
# ------------------------------------------------------------

HUNSPELL_BASE_URL="https://raw.githubusercontent.com/wooorm/dictionaries/main/dictionaries"

FREQUENCYWORDS_BASE_URL="https://raw.githubusercontent.com/hermitdave/FrequencyWords/master/content/2018"

LEIPZIG_DE_URL="https://downloads.wortschatz-leipzig.de/corpora/deu_news_2025_1M.tar.gz"

# ------------------------------------------------------------
# Languages
# ------------------------------------------------------------

LANGUAGES=(
    "es-AR"
    "en-en"
    "de-de"
)

# ------------------------------------------------------------
# Required vocabulary
# ------------------------------------------------------------

ES_AR_REQUIRED=(
    "mañana"
    "pasaría"
    "debería"
    "vos"
    "tenés"
    "podés"
    "querés"
    "hacés"
    "decís"
    "venís"
    "sentís"
    "acá"
    "cuándo"
    "dónde"
)

EN_EN_REQUIRED=(
    "the"
    "have"
    "hello"
)

DE_DE_REQUIRED=(
    "ich"
    "nicht"
    "morgen"
    "entschuldigung"
    "wahrscheinlich"
    "möglicherweise"
)

# ------------------------------------------------------------
# Explicit exclusions
# ------------------------------------------------------------

ES_AR_EXCLUDED=(
    "manana"
)

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------

mkdir -p "${OUTPUT_DIR}"
mkdir -p "${WORK_DIR}"

# Remove only files generated by this script.
rm -f \
    "${OUTPUT_DIR}/es-AR.dict" \
    "${OUTPUT_DIR}/es-AR.deletes" \
    "${OUTPUT_DIR}/en-en.dict" \
    "${OUTPUT_DIR}/en-en.deletes" \
    "${OUTPUT_DIR}/de-de.dict" \
    "${OUTPUT_DIR}/de-de.deletes"

# ------------------------------------------------------------
# Helpers
# ------------------------------------------------------------

print_section() {
    echo
    echo "============================================================"
    echo " $1"
    echo "============================================================"
}

die() {
    echo
    echo "ERROR: $*" >&2
    exit 1
}

require_command() {
    command -v "$1" >/dev/null 2>&1 || die "Required command not found: $1"
}

download_file() {
    local url="$1"
    local destination="$2"

    mkdir -p "$(dirname "${destination}")"

    echo "Downloading:"
    echo "  ${url}"
    echo "To:"
    echo "  ${destination}"

    curl \
        --fail \
        --silent \
        --show-error \
        --location \
        --retry 4 \
        --retry-delay 2 \
        --connect-timeout 30 \
        --max-time 600 \
        "${url}" \
        --output "${destination}"
}

# ------------------------------------------------------------
# Dependency check
# ------------------------------------------------------------

print_section "Checking required tools"

require_command curl
require_command tar
require_command find
require_command wc
require_command python3
require_command ls

echo "Required tools OK."

# ------------------------------------------------------------
# Download Hunspell source
# ------------------------------------------------------------

download_hunspell_dictionary() {
    local language="$1"
    local hunspell_language="$2"

    local destination_dir="${WORK_DIR}/hunspell/${language}"

    mkdir -p "${destination_dir}"

    download_file \
        "${HUNSPELL_BASE_URL}/${hunspell_language}/index.dic" \
        "${destination_dir}/index.dic"

    download_file \
        "${HUNSPELL_BASE_URL}/${hunspell_language}/index.aff" \
        "${destination_dir}/index.aff"
}

# ------------------------------------------------------------
# Download FrequencyWords source
# ------------------------------------------------------------

download_frequency_dictionary() {
    local language="$1"
    local frequency_language="$2"

    local destination="${WORK_DIR}/frequency/${language}.txt"

    mkdir -p "$(dirname "${destination}")"

    download_file \
        "${FREQUENCYWORDS_BASE_URL}/${frequency_language}/${frequency_language}_full.txt" \
        "${destination}"
}

# ------------------------------------------------------------
# Download German Leipzig source
# ------------------------------------------------------------

download_german_frequency() {
    local archive="${WORK_DIR}/leipzig/deu_news_2025_1M.tar.gz"
    local extract_dir="${WORK_DIR}/leipzig/extracted"

    mkdir -p "${WORK_DIR}/leipzig"

    rm -rf "${extract_dir}"
    mkdir -p "${extract_dir}"

    download_file \
        "${LEIPZIG_DE_URL}" \
        "${archive}"

    echo "Extracting German Leipzig corpus..."

    tar \
        --extract \
        --gzip \
        --file="${archive}" \
        --directory="${extract_dir}"

    local corpus_file=""

    corpus_file="$(
        find "${extract_dir}" \
            -type f \
            \( -name "*.txt" -o -name "*.csv" \) \
            -print \
            -quit
    )"

    if [[ -z "${corpus_file}" ]]; then
        corpus_file="$(
            find "${extract_dir}" \
                -type f \
                -print \
                -quit
        )"
    fi

    [[ -n "${corpus_file}" ]] || die "Could not find German Leipzig corpus file."

    printf '%s\n' "${corpus_file}" > "${WORK_DIR}/leipzig/corpus_path.txt"

    echo "German corpus:"
    echo "  ${corpus_file}"
}

# ------------------------------------------------------------
# Download all sources
# ------------------------------------------------------------

print_section "Downloading dictionary sources"

download_hunspell_dictionary "es-AR" "es"
download_hunspell_dictionary "en-en" "en"
download_hunspell_dictionary "de-de" "de"

download_frequency_dictionary "es-AR" "es"
download_frequency_dictionary "en-en" "en"

download_german_frequency

# ------------------------------------------------------------
# Extract Hunspell base words
#
# IMPORTANT:
# Hunspell is NOT used to validate candidates.
# The .dic files are treated purely as vocabulary sources.
# ------------------------------------------------------------

extract_hunspell_words() {
    local language="$1"
    local source="$2"
    local destination="$3"

    python3 - "${source}" "${destination}" <<'PY'
import sys
import unicodedata
from pathlib import Path

source = Path(sys.argv[1])
destination = Path(sys.argv[2])

count = 0

with source.open(
    "r",
    encoding="utf-8",
    errors="replace"
) as src, destination.open(
    "w",
    encoding="utf-8",
    newline="\n"
) as dst:

    first = True

    for raw in src:
        line = raw.rstrip("\r\n")

        if first:
            first = False
            continue

        if not line:
            continue

        # Hunspell dictionary entries can contain flags after "/".
        word = line.split("/", 1)[0]

        word = unicodedata.normalize("NFC", word).lower()

        if word:
            dst.write(word + "\n")
            count += 1

print(count)
PY
}

# ------------------------------------------------------------
# Extract FrequencyWords
# ------------------------------------------------------------

extract_frequencywords() {
    local source="$1"
    local destination="$2"

    python3 - "${source}" "${destination}" "${SOURCE_MAX_ENTRIES}" <<'PY'
import sys
import unicodedata
from pathlib import Path

source = Path(sys.argv[1])
destination = Path(sys.argv[2])
limit = int(sys.argv[3])

def valid_token(word):
    word = unicodedata.normalize("NFC", word).lower()

    if not word:
        return None

    if len(word) > 64:
        return None

    if any(ch.isspace() for ch in word):
        return None

    for ch in word:
        category = unicodedata.category(ch)

        if ch.isalpha():
            continue

        if category.startswith("M"):
            continue

        if ch in ("'", "’", "-"):
            continue

        return None

    return word

count = 0

with source.open(
    "r",
    encoding="utf-8",
    errors="replace"
) as src, destination.open(
    "w",
    encoding="utf-8",
    newline="\n"
) as dst:

    for raw in src:
        if count >= limit:
            break

        line = raw.strip()

        if not line:
            continue

        parts = line.split()

        if not parts:
            continue

        word = valid_token(parts[0])

        if word is None:
            continue

        dst.write(word + "\n")
        count += 1

print(count)
PY
}

# ------------------------------------------------------------
# Extract Leipzig German words
# ------------------------------------------------------------

extract_leipzig_words() {
    local source="$1"
    local destination="$2"

    python3 - "${source}" "${destination}" "${SOURCE_MAX_ENTRIES}" <<'PY'
import sys
import unicodedata
from pathlib import Path

source = Path(sys.argv[1])
destination = Path(sys.argv[2])
limit = int(sys.argv[3])

def valid_token(word):
    word = unicodedata.normalize("NFC", word).lower()

    if not word:
        return None

    if len(word) > 64:
        return None

    if any(ch.isspace() for ch in word):
        return None

    for ch in word:
        category = unicodedata.category(ch)

        if ch.isalpha():
            continue

        if category.startswith("M"):
            continue

        if ch in ("'", "’", "-"):
            continue

        return None

    return word

count = 0

with source.open(
    "r",
    encoding="utf-8",
    errors="replace"
) as src, destination.open(
    "w",
    encoding="utf-8",
    newline="\n"
) as dst:

    for raw in src:
        if count >= limit:
            break

        line = raw.strip()

        if not line:
            continue

        parts = line.split()

        if not parts:
            continue

        # Leipzig frequency files normally contain:
        # rank<TAB>word<TAB>frequency
        candidates = []

        if len(parts) >= 2:
            candidates.append(parts[1])

        candidates.append(parts[0])

        selected = None

        for candidate in candidates:
            selected = valid_token(candidate)

            if selected is not None:
                break

        if selected is None:
            continue

        dst.write(selected + "\n")
        count += 1

print(count)
PY
}

# ------------------------------------------------------------
# Write curated core vocabulary
# ------------------------------------------------------------

write_core_words() {
    local language="$1"
    local destination="$2"

    python3 - "${language}" "${destination}" <<'PY'
import sys
import unicodedata
from pathlib import Path

language = sys.argv[1]
destination = Path(sys.argv[2])

required = {
    "es-AR": [
        "mañana",
        "pasaría",
        "debería",
        "vos",
        "tenés",
        "podés",
        "querés",
        "hacés",
        "decís",
        "venís",
        "sentís",
        "acá",
        "cuándo",
        "dónde",
    ],
    "en-en": [
        "the",
        "have",
        "hello",
    ],
    "de-de": [
        "ich",
        "nicht",
        "morgen",
        "entschuldigung",
        "wahrscheinlich",
        "möglicherweise",
    ],
}

with destination.open(
    "w",
    encoding="utf-8",
    newline="\n"
) as dst:

    seen = set()

    for word in required[language]:
        word = unicodedata.normalize("NFC", word).lower()

        if word not in seen:
            dst.write(word + "\n")
            seen.add(word)
PY
}

# ------------------------------------------------------------
# Build final vocabulary
#
# Priority:
#   1. FrequencyWords / Leipzig
#   2. Hunspell source
#   3. Curated mandatory words
#
# The final limit is enforced while guaranteeing every mandatory
# word remains present.
#
# Spanish accent handling:
#
# FrequencyWords can contain ASCII spellings where the real
# Spanish spelling requires a diacritic, for example:
#
#   mananas  -> mañanas
#   deberia  -> debería
#
# We build an O(N) set of accent-folded keys from Hunspell's
# accented vocabulary. Only the noisy FrequencyWords candidate
# is suppressed. Hunspell itself remains authoritative and is
# still added normally afterward.
#
# This avoids word-by-word Hunspell validation completely.
# ------------------------------------------------------------

build_final_vocabulary() {
    local language="$1"
    local frequency_source="$2"
    local hunspell_source="$3"
    local core_source="$4"
    local destination="$5"

    python3 - "${language}" "${frequency_source}" "${hunspell_source}" "${core_source}" "${destination}" "${SOURCE_MAX_ENTRIES}" <<'PY'
import sys
import unicodedata
from pathlib import Path

language = sys.argv[1]
frequency_source = Path(sys.argv[2])
hunspell_source = Path(sys.argv[3])
core_source = Path(sys.argv[4])
destination = Path(sys.argv[5])
limit = int(sys.argv[6])

# ------------------------------------------------------------
# Explicit exclusions.
#
# These are spelling forms that must never enter the final
# Spanish dictionary, regardless of source.
# ------------------------------------------------------------

excluded = {
    "es-AR": {
        "manana",
        "mananas",
        "deberia",
    },
    "en-en": set(),
    "de-de": set(),
}

# ------------------------------------------------------------
# Normalization
# ------------------------------------------------------------

def normalize_token(word):
    word = unicodedata.normalize("NFC", word).lower()

    if not word:
        return None

    if len(word) > 64:
        return None

    if any(ch.isspace() for ch in word):
        return None

    for ch in word:
        category = unicodedata.category(ch)

        if ch.isalpha():
            continue

        if category.startswith("M"):
            continue

        if ch in ("'", "’", "-"):
            continue

        return None

    return word

# ------------------------------------------------------------
# Accent folding
#
# Examples:
#
#   mañana   -> manana
#   mañanas  -> mananas
#   debería  -> deberia
#   tenés    -> tenes
#
# This is only used to identify ASCII spellings that collide
# with an accented Spanish spelling.
# ------------------------------------------------------------

def accent_key(word):
    decomposed = unicodedata.normalize("NFD", word)

    return "".join(
        ch
        for ch in decomposed
        if not unicodedata.category(ch).startswith("M")
    )

def has_diacritic(word):
    return accent_key(word) != word

# ------------------------------------------------------------
# Read a complete source.
# ------------------------------------------------------------

def read_words(path):
    result = []

    with path.open(
        "r",
        encoding="utf-8",
        errors="replace"
    ) as fh:

        for raw in fh:
            word = raw.rstrip("\r\n")

            if not word:
                continue

            word = normalize_token(word)

            if word is None:
                continue

            if word in excluded[language]:
                continue

            result.append(word)

    return result

# ------------------------------------------------------------
# Read Hunspell first.
#
# Hunspell is still ONLY a vocabulary source.
# It is never executed as a validator.
# ------------------------------------------------------------

hunspell_words = read_words(hunspell_source)

hunspell_set = set(hunspell_words)

# ------------------------------------------------------------
# Build accent collision keys from Hunspell.
#
# For Spanish:
#
#   accented Hunspell word -> accent_key
#
# Example:
#
#   mañanas -> mananas
#   debería -> deberia
#
# This operation is O(N).
# ------------------------------------------------------------

accented_hunspell_keys = set()

if language == "es-AR":
    for word in hunspell_words:
        if has_diacritic(word):
            accented_hunspell_keys.add(
                accent_key(word)
            )

# ------------------------------------------------------------
# Read FrequencyWords.
#
# FrequencyWords is the noisy corpus source. If it contains
# an ASCII word whose accent-folded key corresponds to an
# accented Hunspell spelling, discard that FrequencyWords
# candidate.
#
# IMPORTANT:
# This does NOT remove words from Hunspell.
# Hunspell remains authoritative as a vocabulary source.
# ------------------------------------------------------------

frequency_words = []

accent_filtered_frequency_count = 0

with frequency_source.open(
    "r",
    encoding="utf-8",
    errors="replace"
) as fh:

    for raw in fh:
        word = raw.rstrip("\r\n")

        if not word:
            continue

        word = normalize_token(word)

        if word is None:
            continue

        if word in excluded[language]:
            continue

        if (
            language == "es-AR"
            and word.isascii()
            and accent_key(word) in accented_hunspell_keys
        ):
            accent_filtered_frequency_count += 1
            continue

        frequency_words.append(word)

# ------------------------------------------------------------
# Core vocabulary.
# ------------------------------------------------------------

core_words = read_words(core_source)

# ------------------------------------------------------------
# Merge sources in priority order.
#
#   1. FrequencyWords / Leipzig
#   2. Hunspell
#   3. Core
# ------------------------------------------------------------

ordered = []
seen = set()

def append_unique(words):
    for word in words:
        if word in seen:
            continue

        seen.add(word)
        ordered.append(word)

append_unique(frequency_words)
append_unique(hunspell_words)
append_unique(core_words)

# ------------------------------------------------------------
# IMPORTANT:
#
# At this point we perform a FINAL Spanish accent cleanup.
#
# This catches cases where the unaccented form came from
# Hunspell itself or another source.
#
# Only the explicitly problematic ASCII forms are removed
# here. We do NOT globally remove every ASCII/accent pair,
# because valid Spanish words can legitimately coexist:
#
#   papa / papá
#   si / sí
#   el / él
#   solo / sólo
#
# The broad accent collision filtering already happens against
# FrequencyWords above.
# ------------------------------------------------------------

final_excluded = set(excluded[language])

if language == "es-AR":
    final_excluded.update({
        "manana",
        "mananas",
        "deberia",
    })

# ------------------------------------------------------------
# Prepare mandatory vocabulary.
# ------------------------------------------------------------

core_unique = []

for word in core_words:
    if word not in core_unique:
        core_unique.append(word)

core_set = set(core_unique)

# ------------------------------------------------------------
# Select according to source priority.
# ------------------------------------------------------------

selected = []
selected_set = set()

for word in ordered:
    if word in final_excluded:
        continue

    if word in selected_set:
        continue

    selected.append(word)
    selected_set.add(word)

    if len(selected) >= limit:
        break

# ------------------------------------------------------------
# Guarantee every mandatory word survives the hard limit.
# ------------------------------------------------------------

missing_core = [
    word
    for word in core_unique
    if word not in selected_set
]

for required_word in missing_core:

    # Required words must never be excluded.
    if required_word in final_excluded:
        raise SystemExit(
            f"ERROR: Required word conflicts with exclusion: "
            f"{language}: {required_word}"
        )

    replacement_index = None

    for index in range(len(selected) - 1, -1, -1):
        candidate = selected[index]

        if candidate not in core_set:
            replacement_index = index
            break

    if replacement_index is None:

        if len(selected) < limit:
            selected.append(required_word)
            selected_set.add(required_word)
            continue

        raise SystemExit(
            f"ERROR: Mandatory vocabulary exceeds limit for {language}"
        )

    old_word = selected[replacement_index]

    selected_set.discard(old_word)

    selected[replacement_index] = required_word

    selected_set.add(required_word)

# ------------------------------------------------------------
# Final deterministic normalization/deduplication.
# ------------------------------------------------------------

final_words = []
final_seen = set()

for word in selected:

    word = normalize_token(word)

    if word is None:
        continue

    if word in final_excluded:
        continue

    if word in final_seen:
        continue

    final_seen.add(word)
    final_words.append(word)

# ------------------------------------------------------------
# Enforce maximum vocabulary size.
# ------------------------------------------------------------

if len(final_words) > limit:
    final_words = final_words[:limit]

final_set = set(final_words)

# ------------------------------------------------------------
# Final mandatory-word verification.
#
# This is a set membership check, not Hunspell validation.
# ------------------------------------------------------------

for required_word in core_unique:

    if required_word not in final_set:
        raise SystemExit(
            f"ERROR: Required word was lost while building "
            f"{language}: {required_word}"
        )

# ------------------------------------------------------------
# Explicit Spanish regression protection.
# ------------------------------------------------------------

if language == "es-AR":

    forbidden_spanish = {
        "manana",
        "mananas",
        "deberia",
    }

    forbidden_present = (
        forbidden_spanish.intersection(final_set)
    )

    if forbidden_present:
        words = ", ".join(
            sorted(forbidden_present)
        )

        raise SystemExit(
            f"ERROR: Forbidden Spanish spelling(s) reached "
            f"final vocabulary: {words}"
        )

    required_spanish = {
        "mañana",
        "mañanas",
        "debería",
    }

    missing_spanish = (
        required_spanish.difference(final_set)
    )

    if missing_spanish:
        words = ", ".join(
            sorted(missing_spanish)
        )

        raise SystemExit(
            f"ERROR: Required Spanish accented spelling(s) "
            f"missing: {words}"
        )

# ------------------------------------------------------------
# Write final vocabulary.
# ------------------------------------------------------------

with destination.open(
    "w",
    encoding="utf-8",
    newline="\n"
) as dst:

    for word in final_words:
        dst.write(word + "\n")

print(f"Frequency source: {len(frequency_words)}")
print(f"Hunspell source:  {len(hunspell_words)}")
print(f"Core vocabulary:  {len(core_unique)}")
print(
    "Accent-filtered FrequencyWords: "
    f"{accent_filtered_frequency_count}"
)
print(f"Final vocabulary: {len(final_words)}")
PY
}
# ------------------------------------------------------------
# Create .dict
# ------------------------------------------------------------

create_dictionary() {
    local vocabulary="$1"
    local dictionary="$2"

    {
        printf '%s\n' '#POCKETBOARD-DICT-1'
        cat "${vocabulary}"
    } > "${dictionary}"
}

# ------------------------------------------------------------
# Generate delete candidates
#
# IMPORTANT:
# Deletes are generated ONLY from the final .dict vocabulary.
# Delete keys are NEVER fed back into vocabulary generation.
# ------------------------------------------------------------

generate_deletes() {
    local dictionary="$1"
    local deletes="$2"
    local language="$3"
    local budget="$4"

    python3 - "${dictionary}" "${deletes}" "${language}" "${budget}" "${TOP_DISTANCE2_WORDS}" "${MAX_DELETE_WORD_LENGTH}" "${MAX_DELETES_PER_WORD}" <<'PY'
import sys
import unicodedata
from pathlib import Path

dictionary = Path(sys.argv[1])
deletes = Path(sys.argv[2])
language = sys.argv[3]
budget = int(sys.argv[4])
top_distance2 = int(sys.argv[5])
max_word_length = int(sys.argv[6])
max_deletes_per_word = int(sys.argv[7])

def normalize_word(word):
    return unicodedata.normalize("NFC", word)

words = []

with dictionary.open(
    "r",
    encoding="utf-8",
    errors="strict"
) as fh:

    for raw in fh:
        word = raw.rstrip("\r\n")

        if not word:
            continue

        if word.startswith("#"):
            continue

        words.append(normalize_word(word))

# Dictionary order is intentionally preserved.
# The first TOP_DISTANCE2 words receive distance-2 coverage.
distance2_words = words[:top_distance2]

mapping = {}
entry_count = 0

def add_delete(delete_key, target):
    global entry_count

    if entry_count >= budget:
        return False

    if not delete_key:
        return True

    if delete_key not in mapping:
        mapping[delete_key] = target
        entry_count += 1

        if entry_count >= budget:
            return False

    return True

def generate_distance1(word):
    generated = 0

    for index in range(len(word)):
        delete_key = word[:index] + word[index + 1:]

        before = len(mapping)

        if not add_delete(delete_key, word):
            return generated

        if len(mapping) > before:
            generated += 1

            if generated >= max_deletes_per_word:
                break

    return generated

def generate_distance2(word):
    generated = 0

    first_level = set()

    for index in range(len(word)):
        delete_key = word[:index] + word[index + 1:]
        first_level.add(delete_key)

    for intermediate in sorted(first_level):
        for index in range(len(intermediate)):
            delete_key = (
                intermediate[:index] +
                intermediate[index + 1:]
            )

            before = len(mapping)

            if not add_delete(delete_key, word):
                return generated

            if len(mapping) > before:
                generated += 1

                if generated >= max_deletes_per_word:
                    return generated

    return generated

# ------------------------------------------------------------
# Distance 2 first for high-priority vocabulary.
# ------------------------------------------------------------

for word in distance2_words:
    if entry_count >= budget:
        break

    if len(word) > max_word_length:
        continue

    generate_distance2(word)

# ------------------------------------------------------------
# Distance 1 for the complete final dictionary.
# ------------------------------------------------------------

for word in words:
    if entry_count >= budget:
        break

    if len(word) > max_word_length:
        continue

    generate_distance1(word)

# ------------------------------------------------------------
# Write deterministic delete index.
# ------------------------------------------------------------

with deletes.open(
    "w",
    encoding="utf-8",
    newline="\n"
) as dst:

    dst.write("#POCKETBOARD-DELETES-1\n")
    dst.write("#distance=1,2\n")
    dst.write("#source=dict-only\n")
    dst.write("#delete<TAB>target\n")

    for delete_key in sorted(mapping):
        dst.write(delete_key)
        dst.write("\t")
        dst.write(mapping[delete_key])
        dst.write("\n")

print(f"Generated deletes: {entry_count}")
PY
}

# ------------------------------------------------------------
# Validate dictionary format
# ------------------------------------------------------------

validate_dictionary() {
    local dictionary="$1"
    local language="$2"

    print_section "Checking dictionary: ${language}"

    python3 - "${dictionary}" "${language}" <<'PY'
import sys
import unicodedata
from pathlib import Path

dictionary = Path(sys.argv[1])
language = sys.argv[2]

if not dictionary.is_file():
    raise SystemExit(f"ERROR: Missing dictionary: {dictionary}")

words = []
seen = set()

with dictionary.open(
    "r",
    encoding="utf-8",
    errors="strict"
) as fh:

    lines = fh.readlines()

if not lines:
    raise SystemExit(
        f"ERROR: Empty dictionary: {dictionary}"
    )

if lines[0].rstrip("\r\n") != "#POCKETBOARD-DICT-1":
    raise SystemExit(
        f"ERROR: Invalid dictionary header: {dictionary}"
    )

for raw in lines[1:]:
    word = raw.rstrip("\r\n")

    if not word:
        raise SystemExit(
            f"ERROR: Empty dictionary entry: {dictionary}"
        )

    if word.startswith("#"):
        raise SystemExit(
            f"ERROR: Unexpected comment after header: {dictionary}"
        )

    normalized = unicodedata.normalize("NFC", word)

    if normalized != word:
        raise SystemExit(
            f"ERROR: Dictionary entry is not NFC-normalized: "
            f"{language}: {word}"
        )

    if any(ch.isspace() for ch in word):
        raise SystemExit(
            f"ERROR: Dictionary entry contains whitespace: "
            f"{language}: {word}"
        )

    if word in seen:
        raise SystemExit(
            f"ERROR: Duplicate dictionary word: "
            f"{language}: {word}"
        )

    seen.add(word)
    words.append(word)

if not words:
    raise SystemExit(
        f"ERROR: Dictionary contains no words: {dictionary}"
    )

print(f"Dictionary validation OK: {len(words)} words")
PY
}

# ------------------------------------------------------------
# Validate deletes
# ------------------------------------------------------------

validate_delete_format() {
    local deletes="$1"
    local dictionary="$2"
    local language="$3"

    print_section "Checking deletes: ${language}"

    python3 - "${deletes}" "${dictionary}" "${language}" <<'PY'
import sys
import unicodedata
from pathlib import Path

deletes = Path(sys.argv[1])
dictionary = Path(sys.argv[2])
language = sys.argv[3]

if not deletes.is_file():
    raise SystemExit(
        f"ERROR: Missing deletes file: {deletes}"
    )

if not dictionary.is_file():
    raise SystemExit(
        f"ERROR: Missing dictionary: {dictionary}"
    )

with dictionary.open(
    "r",
    encoding="utf-8",
    errors="strict"
) as fh:

    dictionary_words = {
        line.rstrip("\r\n")
        for line in fh
        if line.rstrip("\r\n")
        and not line.startswith("#")
    }

with deletes.open(
    "r",
    encoding="utf-8",
    errors="strict"
) as fh:

    lines = fh.readlines()

if len(lines) < 4:
    raise SystemExit(
        f"ERROR: Deletes file is too short: {deletes}"
    )

expected_headers = [
    "#POCKETBOARD-DELETES-1",
    "#distance=1,2",
    "#source=dict-only",
    "#delete<TAB>target",
]

for index, expected in enumerate(expected_headers):
    actual = lines[index].rstrip("\r\n")

    if actual != expected:
        raise SystemExit(
            f"ERROR: Invalid deletes header at line {index + 1}: "
            f"{language}: {actual!r}"
        )

seen_delete_keys = set()
entry_count = 0

for line_number, raw in enumerate(lines[4:], start=5):
    line = raw.rstrip("\r\n")

    if not line:
        raise SystemExit(
            f"ERROR: Empty delete entry at line {line_number}: "
            f"{language}"
        )

    if "\t" not in line:
        raise SystemExit(
            f"ERROR: Delete entry without TAB at line "
            f"{line_number}: {language}"
        )

    delete_key, target = line.split("\t", 1)

    if not delete_key:
        raise SystemExit(
            f"ERROR: Empty delete key at line {line_number}: "
            f"{language}"
        )

    if not target:
        raise SystemExit(
            f"ERROR: Empty delete target at line {line_number}: "
            f"{language}"
        )

    delete_key = unicodedata.normalize(
        "NFC",
        delete_key
    )

    target = unicodedata.normalize(
        "NFC",
        target
    )

    if target not in dictionary_words:
        raise SystemExit(
            f"ERROR: Delete target is not in final dictionary: "
            f"{language}: {target}"
        )

    if delete_key in seen_delete_keys:
        raise SystemExit(
            f"ERROR: Duplicate delete key: "
            f"{language}: {delete_key}"
        )

    seen_delete_keys.add(delete_key)
    entry_count += 1

print(f"Delete validation OK: {entry_count} entries")
PY
}

# ------------------------------------------------------------
# Check required vocabulary
#
# IMPORTANT:
# This runs AFTER dictionaries have been created in OUTPUT_DIR.
# ------------------------------------------------------------

check_required_vocabulary() {
    print_section "Checking required vocabulary"

    python3 - \
        "${OUTPUT_DIR}/es-AR.dict" \
        "${OUTPUT_DIR}/en-en.dict" \
        "${OUTPUT_DIR}/de-de.dict" <<'PY'
import sys
import unicodedata
from pathlib import Path

paths = {
    "es-AR": Path(sys.argv[1]),
    "en-en": Path(sys.argv[2]),
    "de-de": Path(sys.argv[3]),
}

required = {
    "es-AR": [
        "mañana",
        "pasaría",
        "debería",
        "vos",
        "tenés",
        "podés",
        "querés",
        "hacés",
        "decís",
        "venís",
        "sentís",
        "acá",
        "cuándo",
        "dónde",
    ],
    "en-en": [
        "the",
        "have",
        "hello",
    ],
    "de-de": [
        "ich",
        "nicht",
        "morgen",
        "entschuldigung",
        "wahrscheinlich",
        "möglicherweise",
    ],
}

for language, path in paths.items():
    if not path.is_file():
        raise SystemExit(
            f"ERROR: Missing dictionary: {path}"
        )

    words = set()

    with path.open(
        "r",
        encoding="utf-8",
        errors="strict"
    ) as fh:

        for raw in fh:
            word = raw.rstrip("\r\n")

            if not word or word.startswith("#"):
                continue

            words.add(
                unicodedata.normalize("NFC", word)
            )

    for required_word in required[language]:
        required_word = unicodedata.normalize(
            "NFC",
            required_word
        )

        if required_word not in words:
            raise SystemExit(
                f"ERROR: Required word missing: "
                f"{language}: {required_word}"
            )

    print(
        f"Required vocabulary OK: {language}"
    )

# ------------------------------------------------------------
# Spanish accent regression checks.
#
# These are explicit regression guards, not Hunspell
# word-by-word validation.
# ------------------------------------------------------------

es_words = set()

with paths["es-AR"].open(
    "r",
    encoding="utf-8",
    errors="strict"
) as fh:

    for raw in fh:
        word = raw.rstrip("\r\n")

        if word and not word.startswith("#"):
            es_words.add(
                unicodedata.normalize("NFC", word)
            )

if "mañana" not in es_words:
    raise SystemExit(
        "ERROR: Spanish regression: 'mañana' is missing"
    )

if "manana" in es_words:
    raise SystemExit(
        "ERROR: Spanish regression: 'manana' must not be present"
    )

if "mananas" in es_words:
    raise SystemExit(
        "ERROR: Spanish regression: 'mananas' must not be present"
    )

if "deberia" in es_words:
    raise SystemExit(
        "ERROR: Spanish regression: 'deberia' must not be present"
    )

if "mañanas" not in es_words:
    raise SystemExit(
        "ERROR: Spanish accent regression: 'mañanas' is missing"
    )

if "debería" not in es_words:
    raise SystemExit(
        "ERROR: Spanish accent regression: 'debería' is missing"
    )

print(
    "Spanish accent regression OK: "
    "mañana present, manana absent; "
    "mañanas present, mananas absent; "
    "debería present, deberia absent"
)
PY
}

# ------------------------------------------------------------
# Check per-language delete budgets
# ------------------------------------------------------------

check_delete_budget() {
    local deletes="$1"
    local budget="$2"
    local language="$3"

    local total_lines
    local entry_count

    total_lines="$(wc -l < "${deletes}")"
    entry_count=$((total_lines - 4))

    if (( entry_count < 0 )); then
        die "Invalid deletes file line count: ${language}"
    fi

    if (( entry_count > budget )); then
        die "Delete budget exceeded: ${language}: ${entry_count} > ${budget}"
    fi

    echo "Delete budget OK: ${language}: ${entry_count}/${budget}"
}

# ------------------------------------------------------------
# Check global delete budget
# ------------------------------------------------------------

check_global_delete_budget() {
    print_section "Checking global delete budget"

    local es_lines
    local en_lines
    local de_lines

    local es_count
    local en_count
    local de_count
    local total

    es_lines="$(wc -l < "${OUTPUT_DIR}/es-AR.deletes")"
    en_lines="$(wc -l < "${OUTPUT_DIR}/en-en.deletes")"
    de_lines="$(wc -l < "${OUTPUT_DIR}/de-de.deletes")"

    es_count=$((es_lines - 4))
    en_count=$((en_lines - 4))
    de_count=$((de_lines - 4))

    total=$((es_count + en_count + de_count))

    if (( total > GLOBAL_DELETE_BUDGET )); then
        die "Global delete budget exceeded: ${total} > ${GLOBAL_DELETE_BUDGET}"
    fi

    echo "es-AR deletes: ${es_count}"
    echo "en-en deletes: ${en_count}"
    echo "de-de deletes: ${de_count}"
    echo "Global deletes: ${total}/${GLOBAL_DELETE_BUDGET}"
    echo "Global delete budget OK."
}

# ------------------------------------------------------------
# Final sanity check
# ------------------------------------------------------------

final_sanity_check() {
    print_section "Final sanity check"

    python3 - \
        "${OUTPUT_DIR}/es-AR.dict" \
        "${OUTPUT_DIR}/en-en.dict" \
        "${OUTPUT_DIR}/de-de.dict" \
        "${OUTPUT_DIR}/es-AR.deletes" \
        "${OUTPUT_DIR}/en-en.deletes" \
        "${OUTPUT_DIR}/de-de.deletes" <<'PY'
import sys
import unicodedata
from pathlib import Path

dict_paths = [
    Path(sys.argv[1]),
    Path(sys.argv[2]),
    Path(sys.argv[3]),
]

delete_paths = [
    Path(sys.argv[4]),
    Path(sys.argv[5]),
    Path(sys.argv[6]),
]

for path in dict_paths:
    if not path.is_file():
        raise SystemExit(
            f"ERROR: Missing final dictionary: {path}"
        )

    with path.open(
        "r",
        encoding="utf-8",
        errors="strict"
    ) as fh:

        words = [
            line.rstrip("\r\n")
            for line in fh
            if line.rstrip("\r\n")
            and not line.startswith("#")
        ]

    if not words:
        raise SystemExit(
            f"ERROR: Final dictionary is empty: {path}"
        )

    if len(words) != len(set(words)):
        raise SystemExit(
            f"ERROR: Final dictionary contains duplicates: {path}"
        )

    for word in words:
        if unicodedata.normalize("NFC", word) != word:
            raise SystemExit(
                f"ERROR: Final dictionary is not NFC-safe: "
                f"{path}: {word}"
            )

for path in delete_paths:
    if not path.is_file():
        raise SystemExit(
            f"ERROR: Missing final deletes file: {path}"
        )

print("Final sanity check OK.")
PY
}

# ------------------------------------------------------------
# Size report
# ------------------------------------------------------------

size_report() {
    print_section "Generated dictionary sizes"

    local language
    local dictionary_size
    local delete_size
    local language_total

    local total_dictionary_bytes=0
    local total_delete_bytes=0
    local total_metadata_bytes=0
    local total_generated_bytes=0
    local total_mib=0

    for language in "${LANGUAGES[@]}"; do
        dictionary_size="$(wc -c < "${OUTPUT_DIR}/${language}.dict")"
        delete_size="$(wc -c < "${OUTPUT_DIR}/${language}.deletes")"

        language_total=$((dictionary_size + delete_size))

        total_dictionary_bytes=$((total_dictionary_bytes + dictionary_size))
        total_delete_bytes=$((total_delete_bytes + delete_size))

        echo "${language}:"
        echo "  .dict:    ${dictionary_size} bytes"
        echo "  .deletes: ${delete_size} bytes"
        echo "  total:    ${language_total} bytes"
    done

    total_generated_bytes=$(
        (
            total_dictionary_bytes +
            total_delete_bytes +
            total_metadata_bytes
        )
    )

    total_mib=$((total_generated_bytes / 1024 / 1024))

    echo
    echo "Total .dict bytes:    ${total_dictionary_bytes}"
    echo "Total .deletes bytes: ${total_delete_bytes}"
    echo "Total metadata bytes: ${total_metadata_bytes}"
    echo "Total generated:      ${total_generated_bytes} bytes"
    echo "Total generated:      ${total_mib} MiB"
}

# ------------------------------------------------------------
# Prepare source word lists
# ------------------------------------------------------------

print_section "Preparing vocabulary sources"

mkdir -p "${WORK_DIR}/words"

extract_hunspell_words \
    "es-AR" \
    "${WORK_DIR}/hunspell/es-AR/index.dic" \
    "${WORK_DIR}/words/es-AR.hunspell.txt" \
    > "${WORK_DIR}/words/es-AR.hunspell.count"

extract_hunspell_words \
    "en-en" \
    "${WORK_DIR}/hunspell/en-en/index.dic" \
    "${WORK_DIR}/words/en-en.hunspell.txt" \
    > "${WORK_DIR}/words/en-en.hunspell.count"

extract_hunspell_words \
    "de-de" \
    "${WORK_DIR}/hunspell/de-de/index.dic" \
    "${WORK_DIR}/words/de-de.hunspell.txt" \
    > "${WORK_DIR}/words/de-de.hunspell.count"

extract_frequencywords \
    "${WORK_DIR}/frequency/es-AR.txt" \
    "${WORK_DIR}/words/es-AR.frequency.txt" \
    > "${WORK_DIR}/words/es-AR.frequency.count"

extract_frequencywords \
    "${WORK_DIR}/frequency/en-en.txt" \
    "${WORK_DIR}/words/en-en.frequency.txt" \
    > "${WORK_DIR}/words/en-en.frequency.count"

leipzig_corpus="$(
    cat "${WORK_DIR}/leipzig/corpus_path.txt"
)"

extract_leipzig_words \
    "${leipzig_corpus}" \
    "${WORK_DIR}/words/de-de.frequency.txt" \
    > "${WORK_DIR}/words/de-de.frequency.count"

write_core_words \
    "es-AR" \
    "${WORK_DIR}/words/es-AR.core.txt"

write_core_words \
    "en-en" \
    "${WORK_DIR}/words/en-en.core.txt"

write_core_words \
    "de-de" \
    "${WORK_DIR}/words/de-de.core.txt"

# ------------------------------------------------------------
# Build final vocabulary
# ------------------------------------------------------------

for language in "${LANGUAGES[@]}"; do
    print_section "Building final vocabulary: ${language}"

    case "${language}" in
        "es-AR")
            frequency_source="${WORK_DIR}/words/es-AR.frequency.txt"
            hunspell_source="${WORK_DIR}/words/es-AR.hunspell.txt"
            core_source="${WORK_DIR}/words/es-AR.core.txt"
            ;;

        "en-en")
            frequency_source="${WORK_DIR}/words/en-en.frequency.txt"
            hunspell_source="${WORK_DIR}/words/en-en.hunspell.txt"
            core_source="${WORK_DIR}/words/en-en.core.txt"
            ;;

        "de-de")
            frequency_source="${WORK_DIR}/words/de-de.frequency.txt"
            hunspell_source="${WORK_DIR}/words/de-de.hunspell.txt"
            core_source="${WORK_DIR}/words/de-de.core.txt"
            ;;

        *)
            die "Unsupported language: ${language}"
            ;;
    esac

    build_final_vocabulary \
        "${language}" \
        "${frequency_source}" \
        "${hunspell_source}" \
        "${core_source}" \
        "${WORK_DIR}/${language}.validated.txt"
done

# ------------------------------------------------------------
# Create final .dict files
# ------------------------------------------------------------

print_section "Creating final dictionaries"

for language in "${LANGUAGES[@]}"; do
    create_dictionary \
        "${WORK_DIR}/${language}.validated.txt" \
        "${OUTPUT_DIR}/${language}.dict"
done

echo "Dictionaries created:"

ls -lh \
    "${OUTPUT_DIR}/es-AR.dict" \
    "${OUTPUT_DIR}/en-en.dict" \
    "${OUTPUT_DIR}/de-de.dict"

# ------------------------------------------------------------
# Generate deletes exclusively from final dictionaries
# ------------------------------------------------------------

print_section "Generating delete indexes"

generate_deletes \
    "${OUTPUT_DIR}/es-AR.dict" \
    "${OUTPUT_DIR}/es-AR.deletes" \
    "es-AR" \
    "${ES_AR_DELETE_BUDGET}"

generate_deletes \
    "${OUTPUT_DIR}/en-en.dict" \
    "${OUTPUT_DIR}/en-en.deletes" \
    "en-en" \
    "${EN_EN_DELETE_BUDGET}"

generate_deletes \
    "${OUTPUT_DIR}/de-de.dict" \
    "${OUTPUT_DIR}/de-de.deletes" \
    "de-de" \
    "${DE_DE_DELETE_BUDGET}"

# ------------------------------------------------------------
# Validate final dictionaries
# ------------------------------------------------------------

validate_dictionary \
    "${OUTPUT_DIR}/es-AR.dict" \
    "es-AR"

validate_dictionary \
    "${OUTPUT_DIR}/en-en.dict" \
    "en-en"

validate_dictionary \
    "${OUTPUT_DIR}/de-de.dict" \
    "de-de"

# ------------------------------------------------------------
# Validate final deletes
# ------------------------------------------------------------

validate_delete_format \
    "${OUTPUT_DIR}/es-AR.deletes" \
    "${OUTPUT_DIR}/es-AR.dict" \
    "es-AR"

validate_delete_format \
    "${OUTPUT_DIR}/en-en.deletes" \
    "${OUTPUT_DIR}/en-en.dict" \
    "en-en"

validate_delete_format \
    "${OUTPUT_DIR}/de-de.deletes" \
    "${OUTPUT_DIR}/de-de.dict" \
    "de-de"

# ------------------------------------------------------------
# Check delete budgets
# ------------------------------------------------------------

print_section "Checking per-language delete budgets"

check_delete_budget \
    "${OUTPUT_DIR}/es-AR.deletes" \
    "${ES_AR_DELETE_BUDGET}" \
    "es-AR"

check_delete_budget \
    "${OUTPUT_DIR}/en-en.deletes" \
    "${EN_EN_DELETE_BUDGET}" \
    "en-en"

check_delete_budget \
    "${OUTPUT_DIR}/de-de.deletes" \
    "${DE_DE_DELETE_BUDGET}" \
    "de-de"

check_global_delete_budget

# ------------------------------------------------------------
# Required vocabulary
#
# This is intentionally AFTER .dict creation.
# ------------------------------------------------------------

check_required_vocabulary

# ------------------------------------------------------------
# Final sanity check
# ------------------------------------------------------------

final_sanity_check

# ------------------------------------------------------------
# Size report
# ------------------------------------------------------------

size_report

# ------------------------------------------------------------
# Final output
# ------------------------------------------------------------

print_section "PocketBoard dictionaries generated successfully"

echo "Output directory:"
echo "  ${OUTPUT_DIR}"

echo
echo "Generated files:"
echo "  ${OUTPUT_DIR}/es-AR.dict"
echo "  ${OUTPUT_DIR}/es-AR.deletes"
echo "  ${OUTPUT_DIR}/en-en.dict"
echo "  ${OUTPUT_DIR}/en-en.deletes"
echo "  ${OUTPUT_DIR}/de-de.dict"
echo "  ${OUTPUT_DIR}/de-de.deletes"

echo
echo "Hunspell validation: DISABLED"
echo "Hunspell role: vocabulary source only"
echo "Spanish accent collision filter: ENABLED"
echo "Delete source: final .dict only"
echo "Maximum delete distance: ${MAX_DISTANCE}"
echo "Top distance-2 vocabulary: ${TOP_DISTANCE2_WORDS}"
echo "Maximum vocabulary size: ${SOURCE_MAX_ENTRIES}"
echo
echo "BUILD DICTIONARIES: OK"
